## Digit Recognition

In [1]:
import keras

In [5]:
import pandas as pd
import numpy as np
import keras
from keras.datasets import mnist
from keras.layers import Dense,Dropout,Flatten,Activation,LeakyReLU,ReLU
from keras.activations import softmax,relu,sigmoid
from keras.models import Sequential

In [6]:
from keras.datasets import mnist

In [8]:
df = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [9]:
(X_train,y_train) , (X_test,y_test) = mnist.load_data()

In [10]:
print(X_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [11]:
print(X_train.shape , y_train.shape)

(60000, 28, 28) (60000,)


In [12]:
print(X_test.shape , y_test.shape)

(10000, 28, 28) (10000,)


In [14]:
print(X_train.shape[0])

60000


## Data Preprocessing

In [16]:
num_classes = 10

X_train = X_train.reshape(X_train.shape[0],28,28,1)
X_test = X_test.reshape(X_test.shape[0],28,28,1)
from keras.utils import to_categorical
y_train = to_categorical(y_train,num_classes)
y_test = to_categorical(y_test,num_classes)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train = X_train/255
X_test = X_test/255
print('X_train_sample',X_train.shape)

X_train_sample (60000, 28, 28, 1)


In [17]:
input_shape = (28,28,1)


In [18]:
from keras.layers import Conv2D,MaxPool2D

## model building

In [21]:
model = Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=input_shape))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes,activation='softmax'))
model.compile(optimizer = 'Adamax' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [22]:
model.fit(X_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0292 - accuracy: 0.9478
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0107 - accuracy: 0.9814
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0077 - accuracy: 0.9874
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0059 - accuracy: 0.9900
Epoch 5/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0049 - accuracy: 0.9919
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0039 - accuracy: 0.9935
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0034 - accuracy: 0.9943
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0029 - accuracy: 0.9956
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0026 - accuracy: 0.9956
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.002

In [24]:
score = model.evaluate(X_test,y_test,verbose=0)
print('test loss',score[0])
print('train_accuracy',score[1])

test loss 0.004983776714652777
train_accuracy 0.9918000102043152
